// Package index renders generated folder indexes from the IR: one
// README.md per directory holding corpus documents. Indexes are
// navigation, never contract — they carry no normative text and are
// excluded from corpus enumeration.
package index

import (
	"fmt"
	"io/fs"
	"path"
	"sort"
	"strings"

	stipulatorv1 "github.com/greatliontech/stipulator/gen/stipulator/v1"
)

// Marker identifies a generated index; fmt refuses to overwrite a
// README.md that lacks it.
const Marker = "<!-- generated by stipulator fmt; do not edit -->"

// Build renders the index for every directory containing at least one
// corpus document, keyed by the README.md path.
func Build(spec *stipulatorv1.Spec) map[string][]byte {
	type docInfo struct {
		path, title string
		reqs        []*stipulatorv1.Requirement
		terms       []string
	}
	byDir := map[string][]*docInfo{}
	docs := map[string]*docInfo{}
	for _, d := range spec.GetDocuments() {
		di := &docInfo{path: d.GetPath(), title: d.GetTitle()}
		docs[d.GetPath()] = di
		dir := path.Dir(d.GetPath())
		byDir[dir] = append(byDir[dir], di)
	}
	for _, r := range spec.GetRequirements() {
		if di, ok := docs[r.GetLocation().GetDocument()]; ok {
			di.reqs = append(di.reqs, r)
		}
	}
	for _, t := range spec.GetTerms() {
		if di, ok := docs[t.GetLocation().GetDocument()]; ok {
			di.terms = append(di.terms, t.GetName())
		}
	}

	out := map[string][]byte{}
	for dir, infos := range byDir {
		sort.Slice(infos, func(i, j int) bool { return infos[i].path < infos[j].path })
		var b strings.Builder
		fmt.Fprintf(&b, "# Index — %s\n\n%s\n\n", dir, Marker)
		b.WriteString("| Document | Title | Requirements | Terms |\n|---|---|---|---|\n")
		for _, di := range infos {
			base := path.Base(di.path)
			fmt.Fprintf(&b, "| [%s](%s) | %s | %d | %d |\n", base, base, di.title, len(di.reqs), len(di.terms))
		}
		for _, di := range infos {
			if len(di.reqs) == 0 {
				continue
			}
			fmt.Fprintf(&b, "\n## %s\n\n", path.Base(di.path))
			for _, r := range di.reqs {
				fmt.Fprintf(&b, "- `%s` (%s, %s)\n", r.GetId(),
					strings.ToLower(strings.TrimPrefix(r.GetKind().String(), "CLAUSE_KIND_")),
					strings.ReplaceAll(strings.ToLower(strings.TrimPrefix(r.GetKeyword().String(), "KEYWORD_")), "_", " "))
			}
		}
		out[path.Join(dir, "README.md")] = []byte(b.String())
	}
	return out
}

// Stale compares the tree's indexes against regeneration: paths whose
// content differs or is absent, plus a refusal error for any existing
// README.md lacking the generation marker.
func Stale(fsys fs.FS, spec *stipulatorv1.Spec, force bool) ([]string, error) {
	want := Build(spec)
	var stale []string
	for p, content := range want {
		raw, err := fs.ReadFile(fsys, p)
		switch {
		case err != nil:
			stale = append(stale, p)
		case !strings.Contains(string(raw), Marker) && !force:
			return nil, fmt.Errorf("%s exists but is not a generated index; move its content into a corpus document or pass force", p)
		case string(raw) != string(content):
			stale = append(stale, p)
		}
	}
	sort.Strings(stale)
	return stale, nil
}
