# proto-file: proto/stipulator/v1/records.proto
# proto-message: stipulator.v1.HardeningSet

records {
  backend: "go"
  symbol: "github.com/greatliontech/stipulator/internal/author.PruneResolvedGaps"
  body_hash: "15238ff58b75d7bbd58208426fcba0c2ef4496d318af45ed3839f07bcd1ac460"
  mutants: 4
  killed: 3
  survivors {
    position: "author.go:399:2"
    operator: "delete statement"
  }
  witness_pins {
    symbol: "github.com/greatliontech/stipulator/internal/author.TestPruneResolvedGaps"
    body_hash: "4efe41e78eacc34e8f6d221f84f5e03b2b19ecd961ec72f2693cf6d7b8dee727"
  }
  operators: "go/2"
  body_line: 392
  toolchain: "go1.26.4-X:nodwarf5 linux/amd64"
}
