# proto-file: proto/stipulator/v1/policy.proto
# proto-message: stipulator.v1.TestPolicy

invocations {
  name: "race"
  timeout {
    seconds: 2700
  }
  go {
    packages: "./..."
    race: true
    args: "-test.timeout=30m"
    bracket_paths: "/bin/sh"
    bracket_paths: "/usr/bin/sh"
    bracket_paths: "/usr/bin/git"
    bracket_paths: "go.work"
  }
}
invocations {
  name: "race:bindingsurface"
  timeout {
    seconds: 2700
  }
  go {
    module_root: "bindingsurface"
    packages: "./..."
    race: true
    bracket_paths: "/bin/sh"
    bracket_paths: "/usr/bin/sh"
    bracket_paths: "/usr/bin/git"
    bracket_paths: "go.work"
    args: "-test.timeout=30m"
  }
}
invocations {
  name: "race:stipulate"
  timeout {
    seconds: 2700
  }
  go {
    module_root: "stipulate"
    packages: "./..."
    race: true
    bracket_paths: "/bin/sh"
    bracket_paths: "/usr/bin/sh"
    bracket_paths: "/usr/bin/git"
    bracket_paths: "go.work"
    args: "-test.timeout=30m"
  }
}
invocations {
  name: "race:stipulate/structural"
  timeout {
    seconds: 2700
  }
  go {
    module_root: "stipulate/structural"
    packages: "./..."
    race: true
    bracket_paths: "/bin/sh"
    bracket_paths: "/usr/bin/sh"
    bracket_paths: "/usr/bin/git"
    bracket_paths: "go.work"
    args: "-test.timeout=30m"
  }
}
